table country_dim
	lineageTag: e70c34cd-6194-4515-8de7-719ba38be0f5

	column country
		dataType: string
		lineageTag: 0139dfcd-7e26-40fb-81d0-1470d6592d82
		summarizeBy: none
		sourceColumn: country

		annotation SummarizationSetBy = Automatic

	column country_key
		dataType: int64
		formatString: 0
		lineageTag: 3520af71-c541-4198-8169-c6ccb28c8ab8
		summarizeBy: none
		sourceColumn: country_key

		annotation SummarizationSetBy = Automatic

	partition country_dim = m
		mode: import
		queryGroup: dimensions
		source =
				let
				  Source = #"winemag-data-source-development",
				  #"Removed Other Columns" = Table.SelectColumns(Source, {"country"}),
				  #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				  #"Sorted Rows" = Table.Sort(#"Removed Duplicates", {{"country", Order.Ascending}}),
				  #"Replaced Blank Values" = Table.ReplaceValue(
				    #"Sorted Rows",
				    "",
				    "Unknown",
				    Replacer.ReplaceValue,
				    {"country"}
				  ),
				  #"Added Index" = Table.AddIndexColumn(#"Replaced Blank Values", "Index", 1, 1, Int64.Type),
				  #"Renamed Columns" = Table.RenameColumns(#"Added Index", {{"Index", "country_key"}})
				in
				  #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

