table province_dim
	lineageTag: 89a3a8d9-4c5e-4a71-8e43-30444c3b1141

	column province
		dataType: string
		lineageTag: a6b8e8b1-eb52-4899-b125-1f4059c4f5be
		summarizeBy: none
		sourceColumn: province

		annotation SummarizationSetBy = Automatic

	column province_key
		dataType: int64
		formatString: 0
		lineageTag: 6a456217-1a88-42d7-bab5-dc1b4289f0ac
		summarizeBy: none
		sourceColumn: province_key

		annotation SummarizationSetBy = Automatic

	partition province_dim = m
		mode: import
		queryGroup: dimensions
		source =
				let
				  Source = #"winemag-data-source-development",
				  #"Removed Other Columns" = Table.SelectColumns(Source, {"province"}),
				  #"Merged country query to filter out country names." = Table.NestedJoin(
				    #"Removed Other Columns",
				    {"province"},
				    country_dim,
				    {"country"},
				    "country_dim",
				    JoinKind.LeftAnti
				  ),
				  #"Removed Uneeded Country Table" = Table.RemoveColumns(
				    #"Merged country query to filter out country names.",
				    {"country_dim"}
				  ),
				  #"Removed Duplicates" = Table.Distinct(#"Removed Uneeded Country Table"),
				  #"Filtered Out Blank Rows" = Table.SelectRows(#"Removed Duplicates", each ([province] <> "")),
				  #"Sorted Rows" = Table.Sort(#"Filtered Out Blank Rows", {{"province", Order.Ascending}}),
				  #"Added Index" = Table.AddIndexColumn(#"Sorted Rows", "Index", 1, 1, Int64.Type),
				  #"Renamed Columns" = Table.RenameColumns(#"Added Index", {{"Index", "province_key"}})
				in
				  #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

